# Generated by Django 4.0.2 on 2022-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email address', max_length=50)),
                ('name', models.CharField(help_text='Enter you name', max_length=150)),
            ],
        ),
    ]
